### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Lukynnnn** [distubejs/example#10]
![image](https://user-images.githubusercontent.com/59299731/147178351-4889d1f4-ef58-4574-85ed-0df79245a35d.png)

**Comment by skick1234** [comment]
![Screenshot_20211223-092818_GitHub~2.png](https://user-images.githubusercontent.com/11555687/147178537-b08f7356-2dd6-4f0f-ae47-fd4c68f65493.png)

**Comment by Lukynnnn** [comment]
I updated everything and nothing.

**Comment by Lukynnnn** [comment]
![image](https://user-images.githubusercontent.com/59299731/147179189-2e5332b2-0f1f-499f-8288-4147ba777bea.png)
new error

**Comment by skick1234** [comment]
![Screenshot_20211223-094005_Edge~2.png](https://user-images.githubusercontent.com/11555687/147179652-e34cbde3-e758-4b90-9452-6d65731b3cef.png)

**Comment by Lukynnnn** [comment]
somehow I don't understand

**Comment by skick1234** [comment]
Just check the docs because you upgraded dependency version which is not backward compatible.

**Comment by Lukynnnn** [comment]
ok, thx
