### ISSUE TITLE
config error

### ISSUE THREAD

**Issue by Swittyss** [distubejs/example#6]
Hello, when I try to play a song, it says:

 An error  encountered: Error: play(music) encountered:
Could not find player config

Config is set so I don't know why it writes.

**Comment by skick1234** [comment]
This is `ytdl-core` error. Maybe it's outdated.
Run `npm i ytdl-core@latest` to update it

**Comment by Swittyss** [comment]
Omg thank you very mutch, my bad sorry. 👍
