### ISSUE TITLE
Resume command not working if the bot is hosted with heroku

### ISSUE THREAD

**Issue by Killmeplz-ops** [distubejs/example#7]
My distube resume command's code:
else if (command ==  'resume') {
        const queque = distube.getQueue(message)
        if (!queque) return message.channel.send('Nothing is playing')
        
        const resumeEmbed = new Discord.MessageEmbed()
        .setTitle(`:play_pause: **RESUMED SONG**`)
        .setDescription(`I have resumed that song`)
        .setColor(`#02caf7`);
       distube.resume(message);
       message.channel.send(resumeEmbed)

**Comment by aeongdesu** [comment]
https://github.com/skick1234/DisTube/issues/75#issuecomment-809867300
